# Generated by Django 3.1.3 on 2020-11-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.CharField(max_length=60)),
                ('comarca', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
    ]
